.PHONY: proto build-node test-orchestrator dev clean

proto:
	@echo "Generating gRPC code..."
	python3 -m grpc_tools.protoc \
		-I proto \
		--python_out=orchestrator/src/arcflare \
		--grpc_python_out=orchestrator/src/arcflare \
		proto/arcflare.proto
	# Fix protobuf imports for Python package structure
	sed -i 's/^import arcflare_pb2 as arcflare__pb2/from . import arcflare_pb2 as arcflare__pb2/' \
		orchestrator/src/arcflare/arcflare_pb2_grpc.py
	# Rust protos are generated by cargo build via tonic-build
	@echo "Python gRPC stubs generated. Rust stubs built via cargo."

build-node:
	cargo build --release -p node-agent

build-splitter:
	cargo build --release -p gguf-splitter

test-orchestrator:
	cd orchestrator && python -m pytest

dev:
	@echo "Starting dev environment..."
	@echo "Ensure you have built the node-agent first: make build-node"
	docker-compose up

clean:
	cargo clean
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete
	rm -rf orchestrator/src/arcflare/*_pb2*.py
