# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arcflare_pb2 as arcflare__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arcflare_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeAgentStub:
    """─── Node Agent Service (runs on each old device) ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/arcflare.NodeAgent/Register',
                request_serializer=arcflare__pb2.RegisterRequest.SerializeToString,
                response_deserializer=arcflare__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/arcflare.NodeAgent/Heartbeat',
                request_serializer=arcflare__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=arcflare__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetHardwareInfo = channel.unary_unary(
                '/arcflare.NodeAgent/GetHardwareInfo',
                request_serializer=arcflare__pb2.Empty.SerializeToString,
                response_deserializer=arcflare__pb2.HardwareReport.FromString,
                _registered_method=True)
        self.RunBenchmark = channel.unary_unary(
                '/arcflare.NodeAgent/RunBenchmark',
                request_serializer=arcflare__pb2.BenchmarkRequest.SerializeToString,
                response_deserializer=arcflare__pb2.BenchmarkResult.FromString,
                _registered_method=True)
        self.SetPerformanceMode = channel.unary_unary(
                '/arcflare.NodeAgent/SetPerformanceMode',
                request_serializer=arcflare__pb2.PerfModeRequest.SerializeToString,
                response_deserializer=arcflare__pb2.PerfModeResponse.FromString,
                _registered_method=True)
        self.GetOverclockingStatus = channel.unary_unary(
                '/arcflare.NodeAgent/GetOverclockingStatus',
                request_serializer=arcflare__pb2.Empty.SerializeToString,
                response_deserializer=arcflare__pb2.OverclockingStatus.FromString,
                _registered_method=True)
        self.CheckDrivers = channel.unary_unary(
                '/arcflare.NodeAgent/CheckDrivers',
                request_serializer=arcflare__pb2.Empty.SerializeToString,
                response_deserializer=arcflare__pb2.DriverReport.FromString,
                _registered_method=True)
        self.ApplySystemTuning = channel.unary_unary(
                '/arcflare.NodeAgent/ApplySystemTuning',
                request_serializer=arcflare__pb2.TuningRequest.SerializeToString,
                response_deserializer=arcflare__pb2.TuningResponse.FromString,
                _registered_method=True)
        self.LoadShard = channel.unary_unary(
                '/arcflare.NodeAgent/LoadShard',
                request_serializer=arcflare__pb2.ShardConfig.SerializeToString,
                response_deserializer=arcflare__pb2.LoadStatus.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/arcflare.NodeAgent/Forward',
                request_serializer=arcflare__pb2.ForwardRequest.SerializeToString,
                response_deserializer=arcflare__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.ForwardStream = channel.stream_stream(
                '/arcflare.NodeAgent/ForwardStream',
                request_serializer=arcflare__pb2.ForwardRequest.SerializeToString,
                response_deserializer=arcflare__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.UnloadShard = channel.unary_unary(
                '/arcflare.NodeAgent/UnloadShard',
                request_serializer=arcflare__pb2.Empty.SerializeToString,
                response_deserializer=arcflare__pb2.Empty.FromString,
                _registered_method=True)
        self.GetInferenceStats = channel.unary_unary(
                '/arcflare.NodeAgent/GetInferenceStats',
                request_serializer=arcflare__pb2.Empty.SerializeToString,
                response_deserializer=arcflare__pb2.InferenceStats.FromString,
                _registered_method=True)


class NodeAgentServicer:
    """─── Node Agent Service (runs on each old device) ───

    """

    def Register(self, request, context):
        """Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareInfo(self, request, context):
        """Hardware
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBenchmark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPerformanceMode(self, request, context):
        """Overclocking & Tuning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverclockingStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDrivers(self, request, context):
        """Drivers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplySystemTuning(self, request, context):
        """System Tuning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadShard(self, request, context):
        """Inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=arcflare__pb2.RegisterRequest.FromString,
                    response_serializer=arcflare__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=arcflare__pb2.HeartbeatRequest.FromString,
                    response_serializer=arcflare__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetHardwareInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareInfo,
                    request_deserializer=arcflare__pb2.Empty.FromString,
                    response_serializer=arcflare__pb2.HardwareReport.SerializeToString,
            ),
            'RunBenchmark': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBenchmark,
                    request_deserializer=arcflare__pb2.BenchmarkRequest.FromString,
                    response_serializer=arcflare__pb2.BenchmarkResult.SerializeToString,
            ),
            'SetPerformanceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPerformanceMode,
                    request_deserializer=arcflare__pb2.PerfModeRequest.FromString,
                    response_serializer=arcflare__pb2.PerfModeResponse.SerializeToString,
            ),
            'GetOverclockingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverclockingStatus,
                    request_deserializer=arcflare__pb2.Empty.FromString,
                    response_serializer=arcflare__pb2.OverclockingStatus.SerializeToString,
            ),
            'CheckDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDrivers,
                    request_deserializer=arcflare__pb2.Empty.FromString,
                    response_serializer=arcflare__pb2.DriverReport.SerializeToString,
            ),
            'ApplySystemTuning': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplySystemTuning,
                    request_deserializer=arcflare__pb2.TuningRequest.FromString,
                    response_serializer=arcflare__pb2.TuningResponse.SerializeToString,
            ),
            'LoadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadShard,
                    request_deserializer=arcflare__pb2.ShardConfig.FromString,
                    response_serializer=arcflare__pb2.LoadStatus.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=arcflare__pb2.ForwardRequest.FromString,
                    response_serializer=arcflare__pb2.ForwardResponse.SerializeToString,
            ),
            'ForwardStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ForwardStream,
                    request_deserializer=arcflare__pb2.ForwardRequest.FromString,
                    response_serializer=arcflare__pb2.ForwardResponse.SerializeToString,
            ),
            'UnloadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadShard,
                    request_deserializer=arcflare__pb2.Empty.FromString,
                    response_serializer=arcflare__pb2.Empty.SerializeToString,
            ),
            'GetInferenceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceStats,
                    request_deserializer=arcflare__pb2.Empty.FromString,
                    response_serializer=arcflare__pb2.InferenceStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arcflare.NodeAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arcflare.NodeAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeAgent:
    """─── Node Agent Service (runs on each old device) ───

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/Register',
            arcflare__pb2.RegisterRequest.SerializeToString,
            arcflare__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/Heartbeat',
            arcflare__pb2.HeartbeatRequest.SerializeToString,
            arcflare__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHardwareInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/GetHardwareInfo',
            arcflare__pb2.Empty.SerializeToString,
            arcflare__pb2.HardwareReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBenchmark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/RunBenchmark',
            arcflare__pb2.BenchmarkRequest.SerializeToString,
            arcflare__pb2.BenchmarkResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPerformanceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/SetPerformanceMode',
            arcflare__pb2.PerfModeRequest.SerializeToString,
            arcflare__pb2.PerfModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverclockingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/GetOverclockingStatus',
            arcflare__pb2.Empty.SerializeToString,
            arcflare__pb2.OverclockingStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/CheckDrivers',
            arcflare__pb2.Empty.SerializeToString,
            arcflare__pb2.DriverReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplySystemTuning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/ApplySystemTuning',
            arcflare__pb2.TuningRequest.SerializeToString,
            arcflare__pb2.TuningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/LoadShard',
            arcflare__pb2.ShardConfig.SerializeToString,
            arcflare__pb2.LoadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/Forward',
            arcflare__pb2.ForwardRequest.SerializeToString,
            arcflare__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/arcflare.NodeAgent/ForwardStream',
            arcflare__pb2.ForwardRequest.SerializeToString,
            arcflare__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/UnloadShard',
            arcflare__pb2.Empty.SerializeToString,
            arcflare__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.NodeAgent/GetInferenceStats',
            arcflare__pb2.Empty.SerializeToString,
            arcflare__pb2.InferenceStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorStub:
    """─── Orchestrator Service (for nodes to report back) ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportNodeStatus = channel.unary_unary(
                '/arcflare.Orchestrator/ReportNodeStatus',
                request_serializer=arcflare__pb2.NodeStatus.SerializeToString,
                response_deserializer=arcflare__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestPartition = channel.unary_unary(
                '/arcflare.Orchestrator/RequestPartition',
                request_serializer=arcflare__pb2.PartitionRequest.SerializeToString,
                response_deserializer=arcflare__pb2.PartitionAssignment.FromString,
                _registered_method=True)


class OrchestratorServicer:
    """─── Orchestrator Service (for nodes to report back) ───

    """

    def ReportNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportNodeStatus,
                    request_deserializer=arcflare__pb2.NodeStatus.FromString,
                    response_serializer=arcflare__pb2.Empty.SerializeToString,
            ),
            'RequestPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPartition,
                    request_deserializer=arcflare__pb2.PartitionRequest.FromString,
                    response_serializer=arcflare__pb2.PartitionAssignment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arcflare.Orchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arcflare.Orchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Orchestrator:
    """─── Orchestrator Service (for nodes to report back) ───

    """

    @staticmethod
    def ReportNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.Orchestrator/ReportNodeStatus',
            arcflare__pb2.NodeStatus.SerializeToString,
            arcflare__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arcflare.Orchestrator/RequestPartition',
            arcflare__pb2.PartitionRequest.SerializeToString,
            arcflare__pb2.PartitionAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
